server:
  port: 8085

spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/siteuser?serverTimezone=Asia/Seoul
    username: sbsst
    password: sbs123414

  jpa:
    properties:
      hibernate:
        show_sql: true
          format_sql:true
        use_sql_comments: true
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    servlet:
      multipart:
        maxFileSize: 1000MB
        maxRequestSize: 1000MB
cloud:
  aws:
    credentials:
      accessKey: ${bucketAccessKey}
      secretKey: ${bucketSecretKey}
    s3:
      bucket: mytrip-bucket
      dir : /
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace